### ISSUE TITLE
Version Check Fail

### ISSUE THREAD

**Issue by Nachtflame** [FoxAhead/Simple-World-Timer#1]
Minor thing really, but perhaps a proper url of *some sort* for version checking?

`[01:50:32] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [simpleworldtimer] Starting version check at http://myurl.me/`
`[01:50:33] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.io.IOException: Server returned HTTP response code: 400 for URL: http://myurl.me/
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)`

**Comment by FoxAhead** [comment]
Thanks! Fixed in 1.1.1. Added version checking.
https://github.com/FoxAhead/Simple-World-Timer/commit/a2db9b62a3f51b572d202dd962e2bd35a2189629
