### ISSUE TITLE
Crash with /swt command, Year 0, and a question about 12-hour times

### ISSUE THREAD

**Issue by katubug** [FoxAhead/Simple-World-Timer#2]
Hello! Firstly, thank you for this mod! I have been looking for a mod that shows the world age instead of just ingame/irl time, so this is fantastic.

1) I did receive a crash when executing the `/swt` command in my main instance. However, in an instance with only SWT, I could not replicate it. I do not have the time to isolate where the conflict might be just now, but I did want to at least report it in case it helped you in some way: https://paste.dimdev.org/axitasopaz.mccrash

2) I have the following setup: https://i.imgur.com/ADr9Kdc.png

But as you can see from that image, it says Year 0 in the HUD, even though it is set to begin at year 1.

3) I am not sure if it would be possible with this current methods, but in an ideal world, I'd love to be able to have 10:23pm instead of 22:23 - it didn't look as though there was a way to do this as of now, would it be something you might consider adding? Totally fine if not, but I thought I'd ask.

Thanks for your time, have a great weekend!

**Comment by FoxAhead** [comment]
Hi!
2 and 3. Have you checked description of java.text.SimpleDateFormat (SDF) class?
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
For your case you can use patterns:
`'Day: &d Time:' hh:mm a`
Lower case `hh` for Hour in am/pm (1-12) and `a` for Am/pm marker.
`'Year: 'Y`
Here SDF `Y` is used instead of additional &Y parameter. The &Y parameter is
> Total played game years from the start year. Zero based. Changes at January 1st 06:00 AM (because game begins at 6AM). Relevant only for Minecraft time.

**Comment by FoxAhead** [comment]
1. Crash should be fixed in v1.1.2. If not, then feel free to reopen issue.

**Comment by katubug** [comment]
Ah, thank you! I did have a look at that link, but I mistakenly assumed that the ampersand was required for all options. Thank you very much for your help, this is perfect.

Also, just tested the new version, and the crash is fixed :D Thank you again!
