### ISSUE TITLE
1.12.2 Total World Time Not Updating

### ISSUE THREAD

**Issue by ScottoMotto** [FoxAhead/Simple-World-Timer#3]
World Time and time in Stopwatch preset remains at 00:00:00, not updating. '[&dd ]'HH:mm:ss
Tested with only SimpleWorldTimer-1.12.2-1.1.3.jar installed.
Both work with SimpleWorldTimer-1.12.2-1.1.2
Serene Seasons not installed.

**Comment by FoxAhead** [comment]
@ScottoMotto
thank you for pointing out this error! It was an annoying miscalculation just in one method. Fixed in 1.12.2-1.1.3.1.
