### ISSUE TITLE
Editing Settings In Game

### ISSUE THREAD

**Issue by solbolt2** [FoxAhead/Simple-World-Timer#6]
Hey!

Is it possible to add the user interface for 1.12.2 to change settings in-game?

They don't seem to let me edit it live? I have to edit the config file and then restart the Minecraft client to update the settings if I want to move the location.

I'm also playing RL Craft btw, if that affects anything.

I looked everywhere for something like this. I'm doing a 100 days hardcore challenge series and needed it to keep track of the days! 
:D Thanks so much!

-Solbolt

**Comment by FoxAhead** [comment]
Hi!
Have you read the description at https://www.curseforge.com/minecraft/mc-mods/simple-world-timer ?

> There is in-game configuration screen bound to H key by default. Or you can alter SimpleWorldTimer.cfg file. Sneaking + H key toggles timer visibility. The chat command /swt is also available in case you want to free the key binding.

**Comment by solbolt2** [comment]
Wow, I saw that too and for some reason just didn't click in my head. Thank
you for the mod! you rock!
