### ISSUE TITLE
Enabling Simple World Timer overlay the XP bar over the level text

### ISSUE THREAD

**Issue by Blizzerac** [FoxAhead/Simple-World-Timer#7]
As the title suggests, turning the mod on in the options by pressing H makes the Level go behind the XP bar. Turning the mod off rectifies that issue.

**Comment by FoxAhead** [comment]
Just tested on SimpleWorldTimer-1.12.2-1.1.3.2 and I can't confirm the issue.
Could you provide more information, please?
Mod version.
Other mods or modpack installed.
Screenshot.

**Comment by Blizzerac** [comment]
Apologies, forgot to tag those along.

**Minecraft Version:** 1.20.1
**Mod Loader:** Forge 47.2.0
**Mod version:** 1.20.1-1.12-beta
**Other mods:**
- 3D Skin Layers
- Aeroblender
- The Aether
- Aether Lost Content
- The Aether: Redux
- Appleskin
- AttributeFix
- Balm
- Better Ping Display
- Blue Skies
- Bookshelf
- Canary
- Chat Heads
- CIT Resewn
- Cloth Config v10 API
- Clumps
- Deep Aether
- DeepslateCutting
- Dungeon Crawl
- Embeddium
- EMI
- EMI Trades
- Emissivity
- EnchantmentDescriptions
- Entity Model Features
- Entity Texture Features
- EntityCulling
- FerriteCore
- GeckoLib4
- ImmediatelyFast
- JourneyMap
- JourneyMap Integration
- JustEnoughItems
- Konkrete
- Make Bubbles Pop
- ModernFix
- MusicManager
- NotEnoughAnimations
- Oculus
- Oculus Particle Fix
- Rubidium Dynamic Lights
- Rubidium Extra
- Rubidium Extras
- Saturn
- Smooth Boot (Reloaded)
- Sound Physics Remastered
- Structure Gel API
- Terrablender
- TexTrue's Embeddium Options
- Trim Effects
- Waystones
- YUNG's API
- YUNG's Better Dungeons
- YUNG's Better Mineshafts
- YUNG's Better Strongholds

**Screenshots:**
https://imgur.com/a/T6nUGqP

**Notes:** 
- Autohide didn't seem to affect the outcome
- Possibly relevant mods: Aether, Embeddium, Oculus

**Comment by FoxAhead** [comment]
Oh. That's a pretty extensive list for me to download and test every mod. Besides, I don't know your exact settings for each mod.
I got no issue on a clean instance in MultiMC:
- LWJGL 3.3.1
- Minecraft 1.20.1
- Forge 47.2.0

with these mods:
- aether-1.20.1-1.0.0-beta.1.3-neoforge.jar
- dynamiclightsreforged-1.20.1_v1.6.0.jar
- embeddium-0.2.2+mc1.20.1.jar
- oculus-mc1.20.1-1.6.9.jar
- simpleworldtimer-1.20.1-1.1.2-beta.jar
- textrues_embeddium_options-0.1.2+mc1.20.1.jar

Used shaders BSL and SEUS.

Could you determine more precisely the mod with which this bug occurs? On my test configuration SWT itself does not cause this glitch.
Also looking at the code, I don't see any possible causes. The only two lines that are related to rendering, and which are enabled/disabled by the `Enable` checkbox, are `guiGraphics.drawString`. Even though I'm not good at MC modding, I don't see any misuse here.
https://github.com/FoxAhead/Simple-World-Timer/blob/2b05fb6f3bc411098896410d70b670803c3c8501/SimpleWorldTimer%201.20.1/src/main/java/foxahead/simpleworldtimer/Timer.java#L116
https://github.com/FoxAhead/Simple-World-Timer/blob/2b05fb6f3bc411098896410d70b670803c3c8501/SimpleWorldTimer%201.20.1/src/main/java/foxahead/simpleworldtimer/Timer.java#L123

**Comment by FoxAhead** [comment]
Ok. I think I found it.

- ImmediatelyFast-1.2.6+1.20.2

The error appears together with this mod.

There are a lot of issues on this mod related to wrong text rendering
Especially
https://github.com/RaphiMC/ImmediatelyFast/issues/129
And other
https://github.com/RaphiMC/ImmediatelyFast/issues/124
https://github.com/RaphiMC/ImmediatelyFast/issues/115
https://github.com/RaphiMC/ImmediatelyFast/issues/91

This mod claims to optimize the rendering including text and HUD, so I assume that the problem is excessive or incorrect optimization.
Since such a glitch occurs not only with my mod, I suggest closing this issue and reopen the issue at the ImmediatelyFast repository.
https://github.com/RaphiMC/ImmediatelyFast/issues

**Comment by Blizzerac** [comment]
Haha yeah sorry, it was a pretty long list. Didn't have time to give more details as I went to bed after. Will reopen the issue there. Thank you!

**Comment by FoxAhead** [comment]
I continued discussion in the ImmediatelyFast issue:
https://github.com/RaphiMC/ImmediatelyFast/issues/129

**Comment by Blizzerac** [comment]
that's awesome man. love your dedication to getting this fixed, appreciate the research into it!
